# docker-compose.yml

version: "3.2"

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:13
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: mutagen_api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecret123
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: secret123
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
