name: Run specs on PR

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests using docker-compose
        run: |
          docker-compose run --rm web bin/rails db:create
          docker-compose up -d db
          docker-compose run --rm -e RAILS_ENV=test web bundle exec rspec
